### ISSUE TITLE
Streaming API?

### ISSUE THREAD

**Issue by alanshaw** [olizilla/instagrab#1]
This is awesome, but could you expose the response stream so I can create an instaproxy? I want to do something like this:

``` js
var http = require('http')
var url = require('url')
var instagrab = require('instagrab')

http.createServer(function (req, res) {
  var qs = url.parse(req.url, true).query
  instagrab(qs.shortcode).pipe(res)
}).listen(8080)
```

**Comment by olizilla** [comment]
Yah! For sure. Will fix and publish today.

**Comment by olizilla** [comment]
For simples we just return the pipe friendly [request](https://github.com/request/request) object
https://github.com/olizilla/instagrab/blob/aa8bc0b54ec166789450604fc4eb1b61094d4d9f/index.js#L55
